version: '3.8'

services:
  gestion-locative:
    build: .
    container_name: gestion_locative
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      # IMPORTANT : On lie le fichier de base de données du NAS vers le conteneur
      # pour que les données soient sauvegardées.
      - ./gestion_locative/db.sqlite3:/app/gestion_locative/db.sqlite3
      # Si vous ajoutez plus tard l'upload de fichiers (factures...), ajoutez une ligne pour /media